### ISSUE TITLE
Error trying to write scorecard to SVG

### ISSUE THREAD

**Issue by keithmuth** [benjamincrom/baseball#1]
In the first repo example, the following code works fine and I can print the JSON string:
```
import baseball
game_id, game = baseball.get_game_from_url('2017-11-1', 'HOU', 'LAD', 1)
game_dict = game._asdict()
game_json_str = game.json()
```

However, following the next block of code to write the JSON to a SVG, I get the following error:
```
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    fh.write(game.get_svg_str())
  File "~/baseball/baseball/example.py", line 427, in get_svg_str
    return get_game_svg_str(self)
  File "~/baseball/baseball/generate_svg.py", line 2072, in get_game_svg_str
    assemble_box_content_dict(game),
  File "~/baseball/baseball/generate_svg.py", line 1982, in assemble_box_content_dict
    svg_content_list = get_svg_content_list(game)
  File "~/baseball/baseball/generate_svg.py", line 1290, in get_svg_content_list
    get_runners_svg(plate_appearance),
  File "~/baseball/baseball/generate_svg.py", line 902, in get_runners_svg
    is_forceout_desc = ('Forceout' in event.run_description or
AttributeError: 'Pitch' object has no attribute 'run_description' 
```

**Comment by benjamincrom** [comment]
Got an update from Keith that this issue is now resolved
